### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by Sen101** [etc5521-2020/assignment-1-brolga#2]
Hello team brolga,
I was struck by the clarity and detail of your well-structured report. First of all, in the choice of problems, these problems are worth studying. Secondly, you've taken missing values into account in your data processing. Thirdly, you chose different graphs on different problems to analyse. But there still are some questions in your repot:
Firstly, you forgot to change the title in the YAML.
Secondly, the best way is to use inline R codes so the numbers are entered by code.
Well done. Very good job.

Thank you
Sen Wang

**Comment by dilinie-seimon** [comment]
Hi Sen,
Thank you for your feedback! Yes, I realize we missed the title, and thanks for the suggestion on improving the reproducibility of the report using inline code.
Dilinie
