### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by mayunk264** [etc5521-2020/assignment-1-brolga#3]
Hello group brolga!

I found your report extremely thorough and well-done. The level of detail was impressive. Specifically, I enjoyed your use of visualisations - figure 4.3 was really well done (the colour scheme and interactivity in particular made it the best plot). The word clouds were also a nice touch. I also liked the use of the 'Data Dictionary' section which helped elucidate variables related to game ratings that I wouldn't have known otherwise.

I had no major issues reproducing your file - except that I had to download the `affin` and `nrc` lexicon packages separately, otherwise the file would not knit.

Great job overall!!!

**Comment by dilinie-seimon** [comment]
Hi Mayunk,
Thanks for the feedback! Really appreciate it.
Dilinie
